#! /bin/sh

export CMD='rm -f *~ .*~'
echo 'Removing backup files...'
echo $CMD
$CMD

export CMD='rm -f *.pyc *.pyo'
echo 'Removing assembled bytecode...'
echo $CMD
$CMD

export CMD='rm -f pGEMcontribution.py pTKRcontributionIterator.py pCALcontributionIterator.py pAEMcontributionIterator.py'
echo 'Removing self written code...'
echo $CMD
$CMD

export CMD='rm -rf IsocDataFile* report'
echo 'Removing Default Root File...'
echo $CMD
$CMD

export CMD='rm -rf doc'
echo 'Removing doxygen doc directory...'
echo $CMD
$CMD

clear; pwd; ls --color=tty;

echo 'Done.'
