#! /bin/env python

import pSafeLogger
logger = pSafeLogger.getLogger('pFastMonTreeProcessor')

from pBaseTreeProcessor import pBaseTreeProcessor
from pFastMonTreeMaker  import FAST_MON_TREE_NAME
from pCustomPlotter     import pCustomPlotter
from pRootFileManager     import pRootFileManager
from pBaseReportGenerator import pBaseReportGenerator

import time


class pFastMonTreeProcessor(pBaseTreeProcessor):

    def __init__(self, xmlParser, inputFilePath, outputFilePath = None):
        pBaseTreeProcessor.__init__(self, xmlParser, inputFilePath,\
                                    FAST_MON_TREE_NAME, outputFilePath)

    def run(self):
        logger.info('Processing the root tree and writing histograms...')
        startTime = time.time()
        self.open()
        self.CustomPlotter = pCustomPlotter(self.OutputFilePath, self.RootTree)
        self.createObjects()
        logger.info('Done in %.2f s.\n' % (time.time() - startTime))
        self.CustomPlotter.cleanup()
        self.close()
    
    ## @brief Create the ROOT objects defined in the enabled output lists
    #  of the xml configuration file.
    ## @param self
    #  The class instance.

    def createObjects(self):
        for rep in self.XmlParser.EnabledPlotRepsDict.values():
            if rep.__class__.__name__ == 'pCUSTOMXmlRep':
                rep.setPlotter(self.CustomPlotter)
            rep.createRootObjects(self.RootTree)




if __name__ == '__main__':
    from pXmlParser import pXmlParser
    from pOptionParser import pOptionParser
    optparser = pOptionParser('crvLV',1,1,False)

    xmlParser = pXmlParser(optparser.Options.c)
    treeProcessor = pFastMonTreeProcessor(xmlParser, optparser.Argument)
    treeProcessor.run()
    # write report if required
    if optparser.Options.r:
        from pErrorHandler        import pErrorHandler
        from pReportGenerator     import pReportGenerator
        REPORT_AUTHOR   = 'Automatically generated by pFastMonTreeProcessor.py'
        errorHandler    = pErrorHandler()
        reportGenerator = pReportGenerator(errorHandler, xmlParser, treeProcessor.OutputFilePath)
        reportGenerator.MAIN_PAGE_TITLE = 'Fast monitor Tree processor report'
        reportGenerator.REPORT_AUTHOR = 'Automatically generated by pFastMonTreeProcessor.py'
        reportGenerator.run(optparser.Options.v)
        if optparser.Options.V:
            reportGenerator.viewReport()

