#! /bin/env python

import pSafeLogger
logger = pSafeLogger.getLogger('pFastMonTreeProcessor')

from pBaseTreeProcessor import pBaseTreeProcessor
from pFastMonTreeMaker  import FAST_MON_TREE_NAME
from pCustomPlotter     import pCustomPlotter
from pRootFileManager     import pRootFileManager
from pBaseReportGenerator import pBaseReportGenerator

import time


class pFastMonTreeProcessor(pBaseTreeProcessor):

    def __init__(self, xmlParser, inputFilePath):
        pBaseTreeProcessor.__init__(self, xmlParser, inputFilePath,\
                                    FAST_MON_TREE_NAME, None)

    def run(self):
        logger.info('Processing the root tree and writing histograms...')
        startTime = time.time()
        self.open()
        self.CustomPlotter = pCustomPlotter(self.OutputFilePath, self.RootTree)
        self.createObjects()
        logger.info('Done in %.2f s.\n' % (time.time() - startTime))
        self.CustomPlotter.cleanup()
        self.close()
    
    ## @brief Create the ROOT objects defined in the enabled output lists
    #  of the xml configuration file.
    ## @param self
    #  The class instance.

    def createObjects(self):
        for rep in self.XmlParser.EnabledPlotRepsDict.values():
            if rep.__class__.__name__ == 'pCUSTOMXmlRep':
                rep.setPlotter(self.CustomPlotter)
            rep.createRootObjects(self.RootTree)


class pFastMonTreeProcessorReportGenerator(pBaseReportGenerator):

    MAIN_PAGE_TITLE = 'Fast monitor Tree processor report'
    REPORT_AUTHOR   = 'Automatically generated by pFastMonTreeProcessor.py'
    
    def __init__(self, treeProcessor):
        self.TreeProcessor = treeProcessor
        self.RootFilePath  = self.TreeProcessor.OutputFilePath
        reportDirPath = self.RootFilePath.replace('.root', '.report')
        pBaseReportGenerator.__init__(self, reportDirPath)
        self.RootFileManager = pRootFileManager()

    def run(self, verbose = False, compileLaTeX = True):
        logger.info('Writing doxygen report files...')
        startTime = time.time()
        self.RootFileManager.openFile(self.RootFilePath)
        self.openReport()
        self.fillMainPage()
        self.createAuxRootCanvas(True, verbose)
        self.addPlots()
        self.deleteAuxRootCanvas()
        self.closeReport()
        self.RootFileManager.closeFile()
        logger.info('Done in %.2f s.\n' % (time.time() - startTime))
        self.compileReport(verbose, compileLaTeX)
        
    def fillMainPage(self):
        self.addSection('main_summary', 'Summary')
        self.write('@n Look at the related pages for details.')

    def addPlots(self):
        for list in self.TreeProcessor.XmlParser.OutputListsDict.values():
            if list.Enabled:
                self.addPlotsList(list)



if __name__ == '__main__':
    from pXmlParser import pXmlParser
    from pOptionParser import pOptionParser
    optparser = pOptionParser('crvLV',1,1,False)

    xmlParser = pXmlParser(optparser.Options.c)
    treeProcessor = pFastMonTreeProcessor(xmlParser, optparser.Argument)
    treeProcessor.run()
    # write report if required
    if optparser.Options.r:
        reportGenerator = pFastMonTreeProcessorReportGenerator(treeProcessor)
        reportGenerator.run(optparser.Options.v, not optparser.Options.L)
        if optparser.Options.V:
            reportGenerator.viewReport()

