
CLOCK_FREQUENCY	 	 = 20000000.
CLOCK_TIC		 = 1./CLOCK_FREQUENCY
CLOCK_ROLLOVER		 = 2**25
NUM_TOWERS               = 16
NUM_TKR_LAYERS_PER_TOWER = 36 
NUM_CAL_LAYERS_PER_TOWER = 8 
NUM_CAL_COLUMN_PER_TOWER = 12 
NUM_ACD_CABLES           = 12 
