#!/bin/env python

from pSafeROOT import ROOT
from pM7Parser import pM7Parser

glat = ROOT.TGraph()
glon = ROOT.TGraph()
galt = ROOT.TGraph()

gjda = ROOT.TGraph()
ggms = ROOT.TGraph()
grol = ROOT.TGraph()

gra = ROOT.TGraph()
gdec= ROOT.TGraph()
gxra = ROOT.TGraph()
gxdec= ROOT.TGraph()
gyra = ROOT.TGraph()
gydec= ROOT.TGraph()

grol = ROOT.TGraph()
gpitch = ROOT.TGraph()
gyaw = ROOT.TGraph()

grock = ROOT.TGraph()
ghor = ROOT.TGraph()
glimb = ROOT.TGraph()

gzl = ROOT.TGraph()
gzb = ROOT.TGraph()

m7FilePath = '/home/bregeon/glast/isoc/bigM7.txt'
p = pM7Parser(m7FilePath)

print p.TimePoints[0]
i=0
for met in p.TimePoints:
    if not (i%10000): print '\revent %d'%i,
    sc = p.getSCPosition((met,0))
    sc.processCoordinates()
    glat.SetPoint(i, sc.GMSTime, sc.getLatitude())
    glon.SetPoint(i, sc.GMSTime, sc.getLongitude())
    galt.SetPoint(i, met, sc.getAltitude())
    gjda.SetPoint(i, met, sc.JulianDate)
    ggms.SetPoint(i, met, sc.GMSTime)
    grol.SetPoint(i, met, sc.getRoll())
    gra.SetPoint(i,  met, sc.getZRa())
    gdec.SetPoint(i, met, sc.getZDec())
    gxra.SetPoint(i, met, sc.getXRa())
    gxdec.SetPoint(i,met, sc.getXDec())
    gyra.SetPoint(i, met, sc.getYRa())
    gydec.SetPoint(i,met, sc.getYDec())
    grol.SetPoint(i, met, sc.getRoll())
    gpitch.SetPoint(i, met, sc.getPitch())
    gyaw.SetPoint(i, met, sc.getYaw())
    grock.SetPoint(i,met, sc.getRockAngle())
    glimb.SetPoint(i,met, sc.getArcAngleEarthLimb())
    ghor.SetPoint(i, met, sc.getLimbAngle())
    gzl.SetPoint(i,  sc.GMSTime, sc.getZGalL())
    gzb.SetPoint(i,  sc.GMSTime, sc.getZGalB())
    i+=1

c = ROOT.TCanvas('Nav','Nav',30,50,1050,850)
c.Divide(2,2)
c.cd(1)
glat.Draw('AP*')
c.cd(2)
glon.Draw('AP*')
c.cd(3)
gyra.Draw('AP*')
c.cd(4)
gydec.Draw('AP*')

c2 = ROOT.TCanvas('Nav2','Nav2',30,50,1050,850)
c2.Divide(2,2)
c2.cd(1)
gxra.Draw('AP*')
c2.cd(2)
gxdec.Draw('AP*')
c2.cd(3)
gra.Draw('AP*')
c2.cd(4)
gdec.Draw('AP*')

c3 = ROOT.TCanvas('Nav3','Nav3',30,50,1050,850)
c3.Divide(2,2)
c3.cd(1)
grol.Draw('AP*')
c3.cd(2)
gpitch.Draw('AP*')
c3.cd(3)
gyaw.Draw('AP*')
c3.cd(4)
grock.Draw('AP*')

c4 = ROOT.TCanvas('Nav4','Nav4',30,50,1050,850)
c4.Divide(2,2)
c4.cd(1)
ghor.Draw('AP*')
c4.cd(2)
glimb.Draw('AP*')
c4.cd(3)
gzl.Draw('AP*')
c4.cd(4)
gzb.Draw('AP*')


glat.GetYaxis().SetTitle('Latitude')
glon.GetYaxis().SetTitle('Longitude')
galt.GetYaxis().SetTitle('Altitude')
gjda.GetYaxis().SetTitle('JulianDate')
ggms.GetYaxis().SetTitle('GMSTime')
grol.GetYaxis().SetTitle('RollAngle')
gra.GetYaxis().SetTitle('ZRa')
gdec.GetYaxis().SetTitle('ZDec')
gxra.GetYaxis().SetTitle('XRa')
gxdec.GetYaxis().SetTitle('XDec')
gyra.GetYaxis().SetTitle('YRa')
gydec.GetYaxis().SetTitle('YDec')
grol.GetYaxis().SetTitle('roll')
gpitch.GetYaxis().SetTitle('pitch')
gyaw.GetYaxis().SetTitle('yaw')
grock.GetYaxis().SetTitle('rock')
ghor.GetYaxis().SetTitle('Horizon')
glimb.GetYaxis().SetTitle('Earth Limb')
gzl.GetYaxis().SetTitle('Z Galactic L')
gzb.GetYaxis().SetTitle('Z Galactic B')

c.Update()
c2.Update()
c3.Update()
c4.Update()
#raw_input('Exit')
