
import os
import sys
import commands
import time

import pUtils

from pBaseReportGenerator import pBaseReportGenerator


class pAlarmReportGenerator(pBaseReportGenerator):

    MAIN_PAGE_TITLE = 'Alarm handler report'
    REPORT_AUTHOR   = 'Automatically generated by pAlarmHandler.py'

    def __init__(self, alarmHandler, forceOverwrite = True):
        self.AlarmHandler = alarmHandler
        pBaseReportGenerator.__init__(self, self.AlarmHandler.ReportDir,\
                                      self.MAIN_PAGE_TITLE             ,\
                                      self.REPORT_AUTHOR               ,\
                                      forceOverwrite)
        self.AlarmsStatusLabels  = ['ERROR', 'WARNING', 'UNDEFINED', 'CLEAN']
        self.SummaryTablesHeader = ['Object name', 'Algorithm', 'Status',\
                                    'Output value', 'Limits', 'details']
        self.SummaryTablesDict   = {}
        for label in self.AlarmsStatusLabels:
            self.SummaryTablesDict[label] = []

    def run(self):
        self.fillSummaryTables()
        self.openReport()
        self.addSection('alarms_output', 'Alarms output')
        for label in self.AlarmsStatusLabels:
            subsectionLabel = 'alarms_%s' % label.lower()
            subsectionTitle = 'Alarms with %s status' % label
            tableName       = 'Alarms table'
            tableCaption    = 'Alarms with %s status.' % label
            self.addSubsection(subsectionLabel, subsectionTitle)
            self.addTable(self.SummaryTablesHeader       ,\
                          self.SummaryTablesDict[label]  ,\
                          tableName, tableCaption)
        self.closeReport()
        self.compileReport()

    def fillSummaryTables(self):
        for alarm in self.AlarmHandler.XmlParser.getEnabledAlarms():
            row = [alarm.RootObject.GetName(), alarm.FunctionName,\
                   alarm.getStatus(), alarm.getValue(), alarm.getLimits(),\
                   'N/A']
            self.SummaryTablesDict[alarm.getStatus()].append(row)
    

if __name__ == '__main__':
    generator = pAlarmReportGenerator('./report', 'Base report')

