
import os
import sys
import logging
import commands
import time

import pUtils

from pBaseReportGenerator import pBaseReportGenerator


class pAlarmReportGenerator(pBaseReportGenerator):

    MAIN_PAGE_TITLE = 'Alarm handler report'

    def __init__(self, outputDirPath, forceOverwrite = True):
        pBaseReportGenerator.__init__(self, outputDirPath ,\
                                      self.MAIN_PAGE_TITLE,\
                                      forceOverwrite = True)

    def openReport(self):
        author = 'Automatically generated by pAlarmHandler.py'
        pBaseReportGenerator.openReport(self, author)
    

if __name__ == '__main__':
    logging.basicConfig(level = logging.DEBUG)
    generator = pAlarmReportGenerator('./report', 'Base report')
    generator.openReport()
    generator.addSection('test', 'test')
    tableHeader = ['a', 'b', 'c'] 
    tableRows   = [['my_test', 2, 3],
                   [4, 5, 6]]
    generator.writeTable(tableHeader, tableRows, 'Howdy, partner?')
    generator.closeReport()
    generator.compileReport()
